name: test-workflow

on:
  push:
    branches: 
      - "release-branch"
      - "test-branch"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: setp1
      run: echo "Hello world release branch"
    - name: step2
      run: |
        echo "hello"
        echo "World"
        date
        pwd
