name: test-workflow

on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: setp1
      run: echo "Hello world from step1"
    - name: step2
      run: |
        echo "hello"
        echo "World"
        date
        pwd
        ls -al
